osx_image: xcode6.4

language: objective-c

before_install: 
# - brew update
# - brew upgrade xctool

script: 
- xctool clean build test -project BButtonDemo.xcodeproj -scheme BButtonDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
